runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: flask
  version: 0.12
- name: click
  version: 6.6
- name: itsdangerous
  version: 0.24
- name: pytz
  version: 2017.3

env_variables:
  CLOUD_SQL_INSTANCE_NAME: game-square-233222:us-central1:game-square
  DB_USER: admin
  DB_PASS: copper
  DB_NAME: TestBase